import 'dart:math';

class AliasEngine {
  static String randomWord(List<String> words) {
    return words[Random().nextInt(words.length)];
  }

  static String get name {
    final newName = randomWord(_adjectives) + randomWord(_nouns);
    return newName;
  }

  static Map<String, String> splitWords(String alias) {
    final List<String> chars = alias.split('');
    for (int i = 2; i < chars.length; i++) {
      String char = alias[i];
      for (final letter in capitalLetters) {
        if (char == letter) {
          final adjective = alias.substring(0, i);
          final noun = alias.substring(i);
          return {"adjective": adjective, "noun": noun};
        }
      }
    }
    return {"adjective": 'adjective', "noun": "noun"};
  }

  static List<String> get _adjectives {
    return [
      "Absolute",
      "Belligerent",
      "Conspicuous",
      "Dastardly",
      "Elaborate",
      "Forgetful",
      "Ginormous",
      "Holistic",
      "Indignant",
      "Jolly",
      "Kafkaesque",
      "Lopsided",
      "Mega",
      "Nuanced",
      "Ordinary",
      "Punctual",
      "Quintessential",
      "Rowdy",
      "Serpentine",
      "Titular",
      "Unnecessary",
      "Vocational",
      "Wayword",
      "Xenial",
      "Yielding",
      "Zombified",
      /////////////////////////////
      "Angry",
      "Bilingual",
      "Cantankerous",
      "Dangerous",
      "Elegant",
      "Frightened",
      "Gargantuan",
      "Holy",
      "Interested",
      "Jubilant",
      "Known",
      "Lengthy",
      "Marvelous",
      "Nice",
      "Open",
      "Playful",
      "Quarrelsome",
      "Reticent",
      "Sanguine",
      "Tepid",
      "Universal",
      "Vigilant",
      "Wrapped",
      //NO X,
      "Yester",
      "Zesty",
      /////////////////////////
      "Angsty",
      "Bountiful",
      "Clandestine",
      "Determined",
      "Enthropic",
      "Flying",
      "Gnarly",
      "Honking",
      "Innocent",
      "Jaded",
      //NO x, No K//
      "Lingering",
      "Myopic",
      "Nonchalant",
      "Ominous",
      "Personified",
      "Quibbling",
      "Raunchy",
      "Sideways",
      "Titanic",
      "Uncouth",
      "Verified",
      "Westerly",
      //
      "Yowling",
      "Zonked",
      //////////////////////////////////////
      "Antsy",
      "Boastful",
      "Classy",
      "Detrimental",
      "Energetic",
      "Frantic",
      "Grateful",
      "Hectic",
      "Isolated",
      "Jynxed",
      //k
      "Laminated",
      "Marked",
      "Narrated",
      "Obsolete",
      "Perfect",
      "Quiet",
      "Rugged",
      "Sunken",
      "Trampled",
      "Unglued",
      "Vast",
      "Wanton",
      "Yearly",
      //NO X, K, Z/
      ////////////////////////////////////////
      "Anti",
      "Brave",
      "Cartoonish",
      "Daring",
      "Excellent",
      "Faint",
      "Glowing",
      "Hungry",
      "Implied",
      "Judicious",
      /////
      "Lackluster",
      "Missed",
      "Noticed",
      "Optimal",
      "Painted",
      "Queasy",
      "Rambling",
      "Sustained",
      "Transient",
      "Uncooked",
      "Vapid",
      "Weird",

      ///x
      ///NO K, X,Y ,Z,
      /////////////////
      ////////////////
      "Analog",
      "Broken",
      "Capricious",
      "Drastic",
      "Emphatic",
      "Flagrant",
      "Glaciated",
      "Hidden",
      "Innocuous",
      // "J"
      //
      "Listless",
      "Moody",
      "Nefarious",
      "Topic-minded",
      "Plausible",
      "Qualified",
      "Rusty",
      "Silly",
      "Tempered",
      "Uppity",
      "Very",
      "Wistful",
      /////////////////////NO J,K,X,Y,Z
      "Apt",
      "Boring",
      "Cranky",
      "Deadly",
      "Elemental",
      "Fictitious",
      "Granular",
      "Habitual",
      "Illicit",
      //j
      //k
      "Lost",
      "Marinated",
      "Noisy",
      "Oaky",
      "Plastic",
      // QQQQ
      "Rabid",
      "Super",
      "Trusted",
      "Unclear",
      "Vernacular",
      "Warranted",
      // //NO J, K, Q, X, Y, Z,
      "Angular",
      "Braided",
      "Corny",
      "Dormant",
      "Empty",
      "Fortified",
      "Gauche",
      "Happy",
      "Ill",
      // No J or K
      "Ludicrous",
      "Moarnful",
      "Omnicient",
      "Palpable",
      //no q
      "Racing",
      "Simple",
      "Torn",
      // "U",
      "Voided",
      "Wriggly",
      //no J, K, Q, U, X, Y, Z,
      "Artic",
      // "B",
      // "C",
      // "D",
    ];
  }

  static List<String> get _nouns {
    return [
      "Antagonist",
      "Butler",
      "Cadavre",
      "Dumbwaiter",
      "Entropy",
      "Firefighter",
      "Grasshopper",
      "Hubbub",
      "Isotope",
      "Janitor",
      "Kitten",
      "Laboratory",
      "Monkeybusiness",
      "Nimrod",
      "Octopus",
      "Plant",
      "Qualm",
      "Road",
      "Sarcasm",
      "Torque",
      "Underdog",
      "Variance",
      "Workstation",
      "Xylophone",
      "Yak",
      "Zenith",
      //////////////////////////////////
      "Astronaut",
      "Bump",
      "Crutch",
      "Doorhinge",
      "Eggplant",
      "Flower",
      "Grain",
      "Hyperbole",
      "Intent",
      "Junkyard",
      "Kinesis",
      "Larynx",
      "Moonshine",
      "Nog",
      "Octave",
      "Pushpin",
      "Quota",
      "Rascal",
      "Sunrise",
      "Trapezoid",
      "Upset",
      "Valor",
      "Werewolf",
      //no x
      "Yule",
      "Zebra",
      ////////////////////////
      "Albatross",
      "Ballpit",
      "Cuckoo",
      "Darkness",
      "Elbow",
      "Fluctuation",
      "Governor",
      "Helipad",
      "Ink",
      "Jester",
      "Kangaroo",
      "Luck",
      "Mouse",
      "Notebook",
      "Oscillation",
      "Platypus",
      "Question",
      "Ruckus",
      "Seaweed",

      "Vacation",
      "Wagon",

      ///
      //NO Y, no X
      "Zeal",
      /////////////////////////
      "Abacus",
      "Button",
      "Coin",
      "Desert",
      "Elephant",
      "Flame",
      "Ghost",
      "Highway",
      "Inchworm",
      "Jello",
      //No K, Y, X
      "Lemon",
      "Motif",
      "Nutmeg",
      "Octagon",
      "Palindrome",
      "Quiz",
      "Rodent",
      "Simplicity",
      "Telephone",
      "Understatement",
      "Vault",
      "Wrinkle",
      //X Y
      ///
      ////
      "Zoo",
      /////////////////
      "Alibi",
      "Brass",
      "Cannon",
      "Deed",
      "Ecology",
      "Forces",
      "Grace",
      "Hideout",
      "Intellect",
      "Joy",

      ///no K, X, Y, z
      "Layover",
      "Map",
      "Noggin",
      "Ocean",
      "Pancreas",
      "Quilt",
      "Railway",
      "Sass",
      "Trio",
      "Understanding",
      "Vapor",
      "Wharf",
      //x/
      ///y
      ///z
      ///////////////////
      "Anthill",
      "Bug",
      "Cantaloupe",
      "Dust",
      "Entrance",
      "Fruit",
      "Grammer",
      "Happenstance",
      "Imp",
      //////NO K, X, Y, Z,
      "Lanyard",
      "Mastodon",
      "Nap",
      "Ox",
      "Post",
      "Quest",
      "Rerun",
      "Sandbox",
      "Tanktop",
      "Umbrella",
      "Vineyard",
      // "W",
      //NO K, W, X, Y, Z
      "Asterisk",
      "Brimstone",
      "Campsite",
      "Drummer",
      "Echo",
      "Flank",
      "Gishgallop",
      "Hug",
      "Inquisition",
      // "Joke",
      //noK
      "Lentil",
      "Mittens",
      "Normativity",
      "Omelet",
      "Punch",
      "Quiver",
      "Rollerrink",
      "Shack",
      "Tornado",
      "Umpire",
      "Void",
      //////////////NO J, K, W, X, Y, Z,
      "Angler",
      "Brush",
      "Chronology",
      "Dork",
      "Etch",
      "Font",
      "Granite",
      "Hunch",
      "Integer",

      //
      ///
      "Obelisk",
      "Plastic",
      // "Q",
      "Rental",
      "Trampoline",
      "Usher",
      "Vase",
      //NO J, K, Q, W, X, Y, Z
    ];
  }

  static List<String> capitalLetters = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ];
}
